config/routes.rb
QuoteMaker::Application.routes.draw do

  root to: 'wallpapers#new'
  
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider

  get "logout"=>"sessions#destroy", as: "logout"
  get "login"=>"sessions#new", as: "login"
  get "signup"=>"users#new", as: "signup"

  
  resources :users, only: [:new, :create,] do
    get 'profile', on: :collection, as: "profile"
  end

  resources :sessions, only: [:new, :create]
  resources :wallpapers, only: [:new, :create, :destroy, :show]
  get "/download/:data" => "wallpapers#download_set", as: "download"

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  authenticates_with_sorcery! do |config|
  	config.authentications_class = Authentication
  end

  has_many :wallpapers

  has_many :authentications, :dependent=>:destroy
  # validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, only: [:profile]
  def new
  	@user = User.new
  end

  def profile
  	@user = current_user
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to root_url, :notice=>"Signed Up!"
  	else
  		render :new
  	end
  end

 
  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
				<li><%=message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="login_signup_form_box">
	<h2>Sign Up</h2>

	<%= form_for @user do |f| %>
		
		<%= render 'errors' %>
		
		<div class="field">
			<%= f.label :name %><br/>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :email %><br/>
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %><br/>
			<%= f.password_field :password %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation %><br/>
			<%= f.password_field :password_confirmation %>
		</div><br/>
		<div class="field">
			<%= f.submit "Thanks" %>
		</div>

	<% end %>
</div>

app/views/users/profile.html.erb
<div class="thumbs-wrapper">
	<% @user.wallpapers.each do |wallpaper|  %>
		<div class="wallpaper-thumbs">
			<div class="wallpaper-img" data-wallpaper-id=<%= wallpaper.id %>><img src=<%= wallpaper.thumb %>></div>	
			<p><%= link_to 'Preview', wallpaper_path(wallpaper.id) %></p>
			<p><%= link_to 'Delete', wallpaper_path(wallpaper.id),  confirm: "Delete this wallpaper?", method: 'DELETE' %></p>
		</div>
	<% end %>
</div>