config/routes.rb
QuoteMaker::Application.routes.draw do

  root to: 'wallpapers#new'
  
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider

  get "logout"=>"sessions#destroy", as: "logout"
  get "login"=>"sessions#new", as: "login"
  get "signup"=>"users#new", as: "signup"

  
  resources :users, only: [:new, :create,] do
    get 'profile', on: :collection, as: "profile"
  end

  resources :sessions, only: [:new, :create]
  resources :wallpapers, only: [:new, :create, :destroy, :show]
  get "/download/:data" => "wallpapers#download_set", as: "download"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
  	redirect_to login_url, :alert=>"First login to access this page"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<div id="nav-bar">
  <div class="nav-buttons"><p><%= link_to("New Wallpaper", new_wallpaper_path) %></p></div>
  <div class="nav-buttons" id="about-button"><p>About</p></div>
  <% if current_user %>
    <div class="nav-buttons"><p><%= link_to("My Profile", profile_users_path) %></p></div>  
  <% else %>
    <div class="nav-buttons"><p><%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %></p></div> 
  <% end %>
  <div class="nav-buttons" id="download-link">
    <%= form_tag( '/download/:data', :method => :get ) do %>
      <%= hidden_field_tag(:ids, value: "") %>
      <%= submit_tag("Download") %>
    <% end %>
  </div>
</div>

app/views/application/_overlay.html.erb
<div class="overlay-wrapper">
  <div class="overlay">
  
  </div>
  <div class="info-box">
    <div id="close-modal">&#10006</div>
    <div class="content">
      <div><p>Quote Maker is an application with the goal of making it easy to create 
        a collection of well-designed desktop wallpapers from your favourite quotes.</p></div>
      <div>
        <h1>Cycle your wallpapers on OSX:</h1>
        <ul>
          <li><p>Open System Preferences</p></li>
          <li><p>Click on "Desktop & Screensaver"</p></li>
          <li><p>Add the folder you'd like to cycle</p></li>
          <li><p>Set your cycle frequency by checking the box labeled: "Change Picture"</p></li>
        </ul>
      </div>
    </div>
  </div>

</div>